name: meetify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.3.0

  # Auth
  google_sign_in: ^6.2.1

  # State Management
  flutter_riverpod: ^3.0.3

  # UI & Icons
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.7.0
  cherry_toast: ^1.13.0

  # ENV
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env
